package:
  name: requests
  version: "2.31.0"

source:
  url: https://pypi.io/packages/source/r/requests/requests-2.31.0.tar.gz
  sha256: 942c5a758f98d790eaed1a29cb6eefc7ffb0d1cf7af05c3d2791656dbd6ad1e1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - charset-normalizer >=2,<4
    - idna >=2.5,<4
    - urllib3 >=1.21.1,<3
    - certifi >=2017.4.17

test:
  imports:
    - requests
  commands:
    - python -c "import requests; print(requests.__version__)"

about:
  home: https://requests.readthedocs.io/
  license: Apache-2.0
  license_file: LICENSE
  summary: Python HTTP library for human beings
  description: |
    Requests is an elegant and simple HTTP library for Python, built for human beings.